# Generated by Django 3.1.14 on 2025-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.EmailField(max_length=254, unique=True)),
                ('message_retention', models.IntegerField(default=0)),
                ('unlimited', models.BooleanField(default=False)),
            ],
        ),
    ]
